Document: music-utilities
Title: Debian music-utilities Manual
Author: <insert document author here>
Abstract: This manual describes what music-utilities is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/music-utilities/music-utilities.sgml.gz

Format: postscript
Files: /usr/share/doc/music-utilities/music-utilities.ps.gz

Format: text
Files: /usr/share/doc/music-utilities/music-utilities.text.gz

Format: HTML
Index: /usr/share/doc/music-utilities/html/index.html
Files: /usr/share/doc/music-utilities/html/*.html
